version: '3.7'

services:
  traefik:
    extends:
      file: ../base/compose.yaml
      service: base-service
    image: 'traefik:v2.5'
    command:
      - '--api.dashboard=true'
      - '--log.level=DEBUG'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entryPoints.http.address=:80'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.dashboard.entrypoints=http'
      - 'traefik.http.routers.dashboard.rule=Host(`$${TRAEFIK_DOMAIN:traefik.indocker.app}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
      - 'traefik.http.routers.dashboard.service=api@internal'
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

networks:
  internal-bridge:
    name: internal-bridge
