services:
  loki:
    image: grafana/loki:2.9.0
    restart: always
    volumes:
      - ./loki:/etc/loki
      - loki-storage:/loki
    ports:
      - "${LOKI_EXPORT_PORT:-3100}:3100"
    expose:
      - 3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

  grafana:
    extends:
      file: ../base/compose.yaml
      service: base-service
    image: grafana/grafana:10.1.0
    restart: always
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN:-grafana.indocker.app}`)'
      - 'traefik.http.routers.grafana.entrypoints=https'
      - 'traefik.http.services.grafana.loadbalancer.server.port=3000'
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      monitoring:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node-exporter:
    image: prom/node-exporter:v1.6.1
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.47.2
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitoring

networks:
  internal-bridge:
    driver: bridge
    external: true
  monitoring:
    name: monitoring
    driver: bridge

volumes:
  prometheus_data:
  grafana-storage:
  loki-storage:
