services:
  adminer:
    extends:
      file: ../base/compose.yaml
      service: base-service
    build:
        context: .
        dockerfile: Dockerfile
        args:
          - VERSION=${ADMINER_VERSION:-4}
    environment:
      ADMINER_DESIGN: ${ADMINER_DESIGN:-pepa-linha-dark}
    networks:
      internal-bridge:
        aliases:
          - adminer
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.adminer.rule=Host(`${ADMINER_DOMAIN:-adminer.indocker.app}`)'
      - 'traefik.http.routers.adminer.entrypoints=https'

networks:
  internal-bridge:
    name: internal-bridge

