version: '3.7'

services:
  adminer:
    build: .
    restart: always
    env_file:
      - adminer.env
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    networks:
      internal-bridge:
        aliases:
          - adminer
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.adminer.rule=Host(`$ADMINER_DOMAIN`)'
      - 'traefik.http.routers.adminer.entrypoints=web'

networks:
  internal-bridge:
    name: internal-bridge

