version: '3.7'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    env_file:
      - postgres.env
    ports:
      - ${POSTGRES_PORT}:5432
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
    networks:
      internal-bridge:
        aliases:
          - postgres

volumes:
  postgres-data:

networks:
  internal-bridge:
    name: internal-bridge
