version: '3.7'

services:
  mongo:
    image: mongo:4
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    env_file:
      - mongo.env
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    networks:
      internal-bridge:
        aliases:
          - mongo

  mongo-express:
    image: mongo-express:latest
    restart: always
    env_file:
      - mongo.env
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    networks:
      internal-bridge:
        aliases:
          - mongo-express
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.me.rule=Host(`$MONGO_EXPRESS_DOMAIN`)'
      - 'traefik.http.routers.me.entrypoints=web'

volumes:
  mongo-data:

networks:
  internal-bridge:
    name: internal-bridge

