version: '3.7'

services:
  redis:
    image: redis:6-alpine
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
    networks:
      internal-bridge:
        aliases:
          - redis
    ports:
      - '6379:6379'

networks:
  internal-bridge:
    name: internal-bridge
